<?php
$tests = [
  /* 
  // examples
  [
    'page' => 'https://www.foo.bar/',
  ],
  [
    'auth' => user/pass,
    'page' => 'https://bar/foo/',
    'response_code' => 200,
    'search_type' => 'xpath',
    'search' => '//*[@id="some-element-id"]',
    'expected_type' => 'element_value',
  ],
  [
    'page' => 'https://bar/baz/',
    'response_code' => 200,
    'search_type' => 'xpath',
    'search' => '//*[@id="edit-trainings"]/option[2]',
    'expected_type' => 'code',
    'expected' => 'if (strlen($got) > 5) return TRUE;',
  ],*/
];
